import logging
import os

UNABLE_TO_FIX_DISTINCT_SIZE_THRESHOLD = os.getenv(
    "UNABLE_TO_FIX_DISTINCT_SIZE_THRESHOLD", 5
)
SMALL_DATASET_LENGTH_THRESHOLD = os.getenv(
    "SMALL_DATASET_LENGTH_THRESHOLD", 300
)
MATCH_ROW_NUM_THRESHOLD = os.getenv("MATCH_ROW_NUM_THRESHOLD", 0.8)
STRING_LENGTH_THRESHOLD = os.getenv("STRING_LENGTH_THRESHOLD", 50)
TYPO_APPEARANCE_FREQUENCY_THRESHOLD = os.getenv(
    "TYPO_APPEARANCE_FREQUENCY_THRESHOLD", 0.3
)
UNABLE_TO_FIX_PLACEHOLDER = os.getenv("UNABLE_TO_FIX_PLACEHOLDER", "-CANT FIX-")
NAN_REPLACE_VALUE = os.getenv("NAN_REPLACE_VALUE", "--NaN--")

NAN_INTEGER = -999999999

logger = logging.getLogger("data_imputation")
logger.setLevel("INFO")
