#!/bin/bash

ISSUES="no"
TOP_LEVEL=$(git rev-parse --show-toplevel)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

remote="$1"
url="$2"

if [[ "$remote" == "" ]]; then
  remote="origin"
fi

if [[ "$remote" != "" ]]; then
  if [[ `git rev-parse HEAD` == `git rev-parse $remote/$CURRENT_BRANCH` ]]; then
    exit 0
  fi
fi

MOD_FILES=$(git diff --name-only $(git rev-parse --abbrev-ref HEAD) $(git merge-base $(git rev-parse --abbrev-ref HEAD) master) | grep -E '\.(py)$')
PREFIXED=$(echo $MOD_FILES | sed -e 's, ,\n,g' | sed -e "s,^,$TOP_LEVEL/,g" | xargs)

if [[ "$MOD_FILES" != "" ]]; then
  if ! flake8 --config $TOP_LEVEL/.flake8 $PREFIXED; then
      ISSUES="yes"
  fi
  if ! black -q --diff --check --color --line-length=88 $PREFIXED; then
      ISSUES="yes"
  fi
fi

if [[ $ISSUES == "no" ]]; then
    GREEN=$'\e[0;32m';
    NC=$'\e[0m';
    if [[ "$remote" == "" ]]; then
      echo "${GREEN}No linting errors detected.${NC}";
    else
      echo "${GREEN}Push allowed. No linting errors detected.${NC}";
    fi
    exit 0
else
    RED=$'\e[0;31m';
    NC=$'\e[0m'
    if [[ $remote == "" ]]; then
      echo "${RED}Please resolve linting issues.${NC}";
    else
      echo "${RED}Push cancelled. Please resolve linting issues or use --no-verify option.${NC}";
    fi
    exit 1
fi
