#!/bin/bash

ISSUES="no"
TOP_LEVEL=$(git rev-parse --show-toplevel)

for FILE in `git diff --name-only `git merge-base master``; do
  # do not check files others than *.py
  if [[ "$TOP_LEVEL/$FILE" == $TOP_LEVEL/actableai/*.py ]]; then
    if ! flake8 --config $TOP_LEVEL/.flake8 $TOP_LEVEL/$FILE; then
        ISSUES="yes"
    fi
  fi
done

if [[ $ISSUES == "no" ]]; then
    GREEN=$'\e[0;32m';
    NC=$'\e[0m';
    echo "${GREEN}No linting errors detected. Push successfull${NC}";
    exit 0
else
    RED=$'\e[0;31m';
    NC=$'\e[0m'
    echo "${RED}Push cancelled. Please resolve linting issues or use the --no-verify option${NC}";
    exit 1
fi
