#!/bin/bash

ISSUES="no"
TOP_LEVEL=$(git rev-parse --show-toplevel)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

remote="$1"
url="$2"

if [[ "$remote" == "" ]]; then
  remote="origin"
fi

if [[ "$remote" != "" ]]; then
  if [[ `git rev-parse HEAD` == `git rev-parse $remote/$CURRENT_BRANCH` ]]; then
    exit 0
  fi
fi

for FILE in `git diff --name-only master`; do
  # do not check files others than *.py
  if [[ "$TOP_LEVEL/$FILE" == $TOP_LEVEL/actableai/*.py ]]; then
    if ! flake8 --config $TOP_LEVEL/.flake8 $TOP_LEVEL/$FILE; then
        ISSUES="yes"
    fi
    if ! black --diff --color --line-length=88 $TOP_LEVEL/$FILE; then
        ISSUES="yes"
    fi
  fi
done

if [[ $ISSUES == "no" ]]; then
    GREEN=$'\e[0;32m';
    NC=$'\e[0m';
    if [[ "$remote" == "" ]]; then
      echo "${GREEN}No linting errors detected.${NC}";
    else
      echo "${GREEN}Push successfull. No linting errors detected.${NC}";
    fi
    exit 0
else
    RED=$'\e[0;31m';
    NC=$'\e[0m'
    if [[ $remote == "" ]]; then
      echo "${RED}Please resolve linting issues.${NC}";
    else
      echo "${RED}Push cancelled. Please resolve linting issues or use --no-verify option.${NC}";
    fi
    exit 1
fi
